name: CI Checks

on:
  pull_request:
    branches:
      - main

jobs:
  run-checks:
    name: Run Linting & Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]  

      - name: Run Linter & Tests
        run: python scripts/lint_and_test.py

